### ISSUE TITLE
[Question] Should urn:tmp be used in production apps, or is it only for demonstration purposes?

### ISSUE THREAD

**Issue by NoelDeMartin** [RubenVerborgh/solid-hue#1]
Looking at [the demo given in Solid World](https://vimeo.com/498076263), I noticed that some of the properties are being declared with `urn:tmp`, which is not a url. I was surprised to see that because I thought every property had to be a url.

I am wondering if that makes sense in this application because the data is auto-generated from an external API and the data is not stored in the Solid POD, so the data in the returned document is "temporary" in that sense. Or is that just because this package is only for demonstration purposes, and this pattern should not be used in production.

Doing a quick search online the only documentation I could find about this pattern is in [this tutorial](https://melvincarvalho.gitbooks.io/solid-tutorials/content/chapter2.html), and it mentions that it shouldn't be used in production.

One of the main problems I face making apps is to define which data structure to use, and as I understand it every property should be declared with a vocabulary that is accessible online as documentation. If I ever need a custom property that is not declared in an existing vocabulary, is it ok to use this kind of thing? For example using `<my-custom-vocabulary:customprop>` instead of `<https://my-custom-vocabulary.com/customprop>` (having to host an ontology on `https://my-custom-vocabulary.com`).

I suppose it is possible technically, but I wonder if it is discouraged for production and considered bad practice.

**Comment by RubenVerborgh** [comment]
> Should urn:tmp be used in production apps, or is it only for demonstration purposes?

There is no strong problem with using URNs (or other URIs) in production;
however, we typically prefer HTTP(S) URLs.

> I was surprised to see that because I thought every property had to be a url.

Not for RDF, they have to be URI.
But for Linked Data, we like to give everything an HTTP/HTTPS URL.

The reason why I used the URN is:
- a quick look at the `dogont` ontology revealed that it would take me like 5 triples just to specify a hue value
- I didn't find another ontology that covered it
- I did not have time to publish an ontology myself

So basically a lack of time; it would need to be replaced indeed.

> I am wondering if that makes sense in this application because the data is auto-generated from an external API and the data is not stored in the Solid POD, so the data in the returned document is "temporary" in that sense.

No, that is not a consideration here.


> Doing a quick search online the only documentation I could find about this pattern is in [this tutorial](https://melvincarvalho.gitbooks.io/solid-tutorials/content/chapter2.html), and it mentions that it shouldn't be used in production.

That's not what it says; it mentions “advisable always to use HTTP URIs”, which I agree with.

> One of the main problems I face making apps is to define which data structure to use, and as I understand it every property should be declared with a vocabulary that is accessible online as documentation. If I ever need a custom property that is not declared in an existing vocabulary, is it ok to use this kind of thing? For example using `<my-custom-vocabulary:customprop>` instead of `<https://my-custom-vocabulary.com/customprop>` (having to host an ontology on `https://my-custom-vocabulary.com`).

You can do it, but I would not recommend it:

- The problem with using `urn:` is that apps cannot look them up as they can with `http:` URIs.
- The problem with `urn:tmp` specifically is that it is not governed; so anybody can “put” anything there.

> I suppose it is possible technically, but I wonder if it is discouraged for production and considered bad practice.

I would not do it indeed.

**Comment by NoelDeMartin** [comment]
Cool, that solves my doubts :). Thanks.
